### ISSUE TITLE
raise InvalidSchema("No connection adapters were found for '%s'" % url)

### ISSUE THREAD

**Issue by gerrydoro** [MrUke/Scuolabook-downloader#3]
```
gerardo@VMelementary:~/Documenti/Scuolabook-downloader-master$ python3 download.py 
Your '_turner_session' key: TmR0YU1JZm1Ta05qeHRxVDRhbVJFYUgxWTJTM1pZVmpxbWRpVGI0bjhwc2lnTnhBckhDbzJGWmtyeVlIbW50Vm5RenZvNUoyT2U2UG8rSC81dXdxOHpTSUZ1Rm1xMjk3bExTN2NPMGZKMFFZcUVjYXh1SjU2UFZtQTFhTENoTHVMWTFhWHdkSmlzU0hDRytaUkJ0Q3NlaFFVNnZjZWVub1B0QTViWXl0WE9oRnhkYWpjMFR6WVkxM1JYL1BTWXQwdFg2MWxQenJwS0lBMkRxTlBHUVh5cEFIUDVUODdYekdYWTgvOGlEblp0MnlWV3c4QXBnOE5NbWFwTEZYVGs0S0x4RmJJVnJYMDJBa1F4TXorRkk5Q28rbTNNcmM5YnZFZDVUU2gxM2VORG5tM1d1bFNTWDNLZytHN1ZaZHdXQVVlWmUrVEdZUVgzSHlMTlVZTWJNMzFTUXFDcEFVUy9DaFdUNzRtM1daKzhDUTZRL0wwdW5RSGptL1o3emZscWZFZGJZbzFaQlhZaTZGcEdEcEU4ZnZwU29NVjdPUnAxTHhyaHkyUk13c1kvMU1ldksySnhmUDQwN3AyTmx2K0lQZ3lMTm5BZW95M1pFOW9SSjY2UUxoSFYyd0s2Qnl2Qnhna0dNemxYY2QzTy9VMDFTK1E3d3BjMjl3dDQwUmpHN0taT0g5K0FMdEh2dkVjdE5GcGFDQTIveEhOY1VMbllGM3IrNXFKaWo5SDRJYnNrZDRrWWRxUUEwRFJOTjRmNmtBTVUwdXllbHl1aEwzR1lzb2dFT2lmd0M2Y2ZhbXNsTm5DUzh2d2dCMzl1aUk2elRlaXZqc3pYUTBjcmdnNXhra2drVFhLcmxnTjVCRkpJdlI1aEtJWHFzeUdrRFFHY3JzWE9RRU5OZjltSkp6SzhsQVZGY2d4MlhONExZQ1dnb3FJU1VSaXczN2hPK3ZkZUJYWTUrYmNYK0RIUjZNaXVTQ3VMaFdUemVDZGUyL1BEcHJ4VWJsaGcrWTR5YVQ0T2g0VzBHYkRDWmIrVTBHRGpwTFB3N1BLWXNjaVR6bEdEb3ZiZ1NXTEpIaW5nR0l1VEVhVjh1YVBQelNOVHhScnFZL0NtT29EemEyNFpaaVk5Mk9BbTZscWRxQWVCbDhBemdDZ254K3FjdmJ1U0FxMllOaTl1Y3BkM2dBRjZwT1MwbXcyeXVKVWFDU2pZVzFieit4VjV5NWJjVlVLQ1diUDlmd3ZUT3J0VFB6QkhMZ09zMFBYYnExQ3NyeDFGWVNZUGdtcDRjaFZsVk4zK3lldmJyTkNUcEVrQ1ZkRHFPVjNWUi9sa1R4MklyalBocz0tLWNiK2k0TXZBNjVYbUZsUVdjajdKdFE9PQ%3D%3D--e168065fc895e3783dbf1647b1d3b0a972eac0ba

[Your library]

290)    Corso di informatica - Volume 1
459)    TECNOLOGIE INFORMATICHE - RELEASE 2.0
1931)   LINGUAGGI WEB - LATO SERVER E MOBILE COMPUTING
1328)   LINGUAGGI WEB - LATO CLIENT

Insert book ID to download: 1328

[Selected book]

Title: 'b'LINGUAGGI WEB - LATO CLIENT''
Author: b'A. Lorenzi, R. Giupponi, D. Iovino' 
Publisher: b'Istituto Italiano Edizioni Atlas' 
ISBN: b'9788826891118' 
Pages: 256 

Downloading page 1/256...Traceback (most recent call last):
  File "download.py", line 57, in <module>
    f.write(requests.get(link).content)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 553, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 598, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'b'https://cdn-webreader.scuolabook.it/scuolabook/img_h/atlas_91118/1.jpg?Expires=1475533824&Signature=tVHTnJHOnNNODGXRJgLKwmJHPqT-AcyZitfe07prruUBBe40EV8JTf3H2lok3JY0diz3pbOxh8UV5eA5mI-wmcD9eVxFNDM3ucTiZYCutDoR-xgewJ1asTcP33-OMnSajZgQ7DvY8yEIcy61M6n0WFqvyl7zu11cUX1trqmJ1A4_&Key-Pair-Id=APKAIOUHYX2EW7R6WUJA''
gerardo@VMelementary:~/Documenti/Scuolabook-downloader-master$
```

Questa volta ho usato python3 e ho installato tutti i moduli necessari con pip3.

**Comment by ale00** [comment]
Dovrebbe essere un problema di rete, non del programma.

**Comment by gerrydoro** [comment]
Errore mio, stavo facendo il tutto su **elementaryOS** in **VMware** ma sembrerebbe che a python non piacciano le schede di rete virtuali. Ho provato a settare la rete in VMware sia in _bridge_ che in _NAT_ ma niente. 
Chiudo.
